#!/bin/sh
# gen-fixture.sh — deterministically (re)generates e2e/scale/aws/config and
# e2e/scale/aws/credentials: a ~500-profile scale fixture for faws.
#
# Re-run any time with no arguments; output is byte-for-byte identical run to
# run (no randomness, no timestamps, no host-specific paths — credential_process
# lines carry the __FAWS_E2E_ROOT__ placeholder, substituted at test/sample-run
# time, exactly like e2e/aws/config does for the small fixture):
#
#   ./e2e/scale/gen-fixture.sh
#
# --- The distribution (also documented in e2e/scale/README.md) ---
#
# Base population — 480 SSO-style profiles, fully algorithmic:
#   24 orgs (org00..org23) x 5 accounts (acct0..acct4) x 4 roles
#   (ReadOnly, PowerUser, Admin, ReadOnlyPlus) = 480.
#   Account id = printf '%02d%08d%02d' <org> 0 <acct> (12 digits; the org
#   index is its first two digits, the account index its last two).
#   Region cycles through a fixed list of 6, keyed by a running counter.
#
# Then 20 hand-built adversarial profiles chosen to break a naive
# implementation (prefix-overlapping names, role-substring hazards,
# near-identical account ids, unicode names, a 200+ char name, an empty role
# value, two role_arn/source_profile chains, two uppercase-secret-key
# profiles whose secret VALUES contain common filter words, two mfa_serial
# profiles, two oddly-cased-key profiles) plus one [sso-session] and one
# [services] block, which must still be skipped as non-profiles.
#
# e2e/scale/aws/credentials carries 20 bare [name] sections: 4 deliberately
# collide with config profile names (to exercise the config-wins precedence
# rule at scale) and 16 are new credsonly-NN profiles found nowhere else.
#
# scale_test.go computes every expected filter count from these same rules
# (an independently written model + a from-spec re-implementation of the
# AND/OR/exclude algorithm), never from a number pasted out of a run.
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
OUT_DIR="$SCRIPT_DIR/aws"
mkdir -p "$OUT_DIR"
CONFIG="$OUT_DIR/config"
CREDS="$OUT_DIR/credentials"

VENDOR='__FAWS_E2E_ROOT__/fake-credential-process'

# ---------------------------------------------------------------------------
# aws/config
# ---------------------------------------------------------------------------
cat >"$CONFIG" <<'HEADER'
# faws e2e/scale fixture — AWS config, generated by gen-fixture.sh. DO NOT
# EDIT BY HAND; edit the generator and re-run it instead.
#
# __FAWS_E2E_ROOT__ is substituted with the absolute path of e2e/ (this
# fixture's parent directory, where fake-credential-process actually lives)
# when the file is rendered by scale_test.go / run-samples.sh into a temp
# dir, exactly as e2e/aws/config does for the small fixture.
#
# Not a profile: proves [sso-session ...] is still skipped at scale.
[sso-session scale-session]
sso_start_url = https://scale.awsapps.com/start
sso_region    = us-east-1

# Not a profile: proves [services ...] is still skipped at scale.
[services scale-services]
s3 =
  endpoint_url = https://example.invalid

HEADER

regions="us-east-1 us-west-2 eu-west-1 ap-southeast-2 eu-central-1 ca-central-1"
set -- $regions
nregions=$#
i=0
org=0
while [ "$org" -le 23 ]; do
	orgNN=$(printf '%02d' "$org")
	start_url="https://org${orgNN}.awsapps.com/start"
	acct=0
	while [ "$acct" -le 4 ]; do
		acctid=$(printf '%02d%08d%02d' "$org" 0 "$acct")
		for role in ReadOnly PowerUser Admin ReadOnlyPlus; do
			ridx=$((i % nregions + 1))
			eval "region=\${$ridx}"
			name="org${orgNN}-acct${acct}/${role}"
			cat >>"$CONFIG" <<EOF
[profile ${name}]
granted_sso_start_url  = ${start_url}
granted_sso_region     = us-east-1
granted_sso_account_id = ${acctid}
granted_sso_role_name  = ${role}
region                 = ${region}
credential_process     = ${VENDOR} ${name}

EOF
			i=$((i + 1))
		done
		acct=$((acct + 1))
	done
	org=$((org + 1))
done

# --- 20 hand-built adversarial profiles ---

# Build a 200+ char name: "longname-" (9 chars) + 220 'x' + "/ReadOnly" (9
# chars) = 238 chars total.
longx=""
n=0
while [ "$n" -lt 220 ]; do
	longx="${longx}x"
	n=$((n + 1))
done
longname="longname-${longx}/ReadOnly"

cat >>"$CONFIG" <<EOF
# --- adversarial: 2 names that are prefixes of each other. NOTE: deliberately
# NOT "app"/"app-extra" — every SSO-style profile in this fixture (base and
# adversarial alike) carries a granted_sso_start_url of the form
# https://*.awsapps.com/start, which itself contains the substring "app": a
# prefix-pair fixture named "app" would make --all app match almost the
# entire fixture via that start url, not just the two intended profiles.
# "nimbus" appears nowhere else in this fixture.
[profile nimbus]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000001
granted_sso_role_name  = ReadOnly
region                 = us-east-1
credential_process     = ${VENDOR} nimbus

[profile nimbus-extra]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000002
granted_sso_role_name  = ReadOnly
region                 = us-east-1
credential_process     = ${VENDOR} nimbus-extra

# --- adversarial: role names where one contains another (3-way chain) ---
[profile roletest/Deploy]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000003
granted_sso_role_name  = Deploy
region                 = us-east-1
credential_process     = ${VENDOR} roletest/Deploy

[profile roletest/DeployAdmin]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000004
granted_sso_role_name  = DeployAdmin
region                 = us-east-1
credential_process     = ${VENDOR} roletest/DeployAdmin

[profile roletest/DeployAdminPlus]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000005
granted_sso_role_name  = DeployAdminPlus
region                 = us-east-1
credential_process     = ${VENDOR} roletest/DeployAdminPlus

# --- adversarial: account ids sharing a long prefix, last digits differ ---
[profile acctclose-a/ReadOnly]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000010
granted_sso_role_name  = ReadOnly
region                 = us-east-1
credential_process     = ${VENDOR} acctclose-a/ReadOnly

[profile acctclose-b/ReadOnly]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000011
granted_sso_role_name  = ReadOnly
region                 = us-east-1
credential_process     = ${VENDOR} acctclose-b/ReadOnly

[profile acctclose-c/ReadOnly]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000012
granted_sso_role_name  = ReadOnly
region                 = us-east-1
credential_process     = ${VENDOR} acctclose-c/ReadOnly

# --- adversarial: non-ASCII names ---
[profile café-prod/ReadOnly]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000020
granted_sso_role_name  = ReadOnly
region                 = us-east-1
credential_process     = ${VENDOR} café-prod/ReadOnly

[profile 東京-dev/ReadOnly]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000021
granted_sso_role_name  = ReadOnly
region                 = us-east-1
credential_process     = ${VENDOR} 東京-dev/ReadOnly

# --- adversarial: a 200+ char name ---
[profile ${longname}]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000030
granted_sso_role_name  = ReadOnly
region                 = us-east-1
credential_process     = ${VENDOR} ${longname}

# --- adversarial: an empty-ish role value (key present, value empty) ---
[profile emptyrole-profile]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000040
granted_sso_role_name  =
region                 = us-east-1
credential_process     = ${VENDOR} emptyrole-profile

# --- adversarial: role_arn + source_profile chains. Never vended by any test
# or sample: resolving them for real needs a genuine sts:AssumeRole network
# call, which this suite must never make. Visible to filtering only.
[profile chain-a]
role_arn       = arn:aws:iam::990000000050:role/ChainRoleA
source_profile = chain-base-a

[profile chain-b]
role_arn       = arn:aws:iam::990000000051:role/ChainRoleB
source_profile = chain-base-b

# --- adversarial: UPPERCASE secret keys whose secret VALUES contain common
# filter words. A correct faws must never match on aws_access_key_id /
# aws_secret_access_key regardless of the key's case in the file (cutKV
# lowercases keys; filter.SecretKeys excludes the lowercased names).
[profile shouty-scale-a]
AWS_ACCESS_KEY_ID     = AKIAFAKESCALE0000001
AWS_SECRET_ACCESS_KEY = uppercase-secret-scale-bait-readonly

[profile shouty-scale-b]
AWS_ACCESS_KEY_ID     = AKIAFAKESCALE0000002
AWS_SECRET_ACCESS_KEY = UPPERCASE-SECRET-SCALE-BAIT-ADMIN

# --- adversarial: mfa_serial profiles, for MFA counting/ordering at scale ---
[profile mfa-a/ReadOnly]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000060
granted_sso_role_name  = ReadOnly
region                 = us-east-1
mfa_serial             = arn:aws:iam::990000000060:mfa/scale-a
credential_process     = ${VENDOR} mfa-a/ReadOnly

[profile mfa-b/PowerUser]
granted_sso_start_url  = https://scale-adversarial.awsapps.com/start
granted_sso_region     = us-east-1
granted_sso_account_id = 990000000061
granted_sso_role_name  = PowerUser
region                 = us-east-1
mfa_serial             = arn:aws:iam::990000000061:mfa/scale-b
credential_process     = ${VENDOR} mfa-b/PowerUser

# --- adversarial: keys in unusual case, e.g. Granted_SSO_Role_Name. cutKV
# lowercases every key it reads, so these must behave identically to the
# lowercase form above (correct account/role display, correct filtering).
[profile casecheck-a/ReadOnly]
Granted_SSO_Start_Url  = https://scale-adversarial.awsapps.com/start
Granted_SSO_Region     = us-east-1
Granted_SSO_Account_Id = 990000000070
Granted_SSO_Role_Name  = ReadOnly
region                 = us-east-1
credential_process     = ${VENDOR} casecheck-a/ReadOnly

[profile casecheck-b/PowerUser]
Granted_SSO_Start_Url  = https://scale-adversarial.awsapps.com/start
Granted_SSO_Region     = us-east-1
Granted_SSO_Account_Id = 990000000071
Granted_SSO_Role_Name  = PowerUser
region                 = us-east-1
credential_process     = ${VENDOR} casecheck-b/PowerUser
EOF

# ---------------------------------------------------------------------------
# aws/credentials — 20 bare [name] sections: 4 deliberately collide with
# config profile names (config must win), 16 are new credsonly-NN profiles.
# Each collision carries a "note" marker value found nowhere in the config
# version, so a filter on that marker proves the credentials-file copy was
# dropped rather than merged or preferred.
# ---------------------------------------------------------------------------
cat >"$CREDS" <<'EOF'
# faws e2e/scale fixture — AWS shared credentials file, generated by
# gen-fixture.sh. DO NOT EDIT BY HAND; edit the generator and re-run it.
#
# 4 sections below collide with config profile names on purpose (config must
# win); each carries a "note = credswins-..." marker that must never surface
# through a filter, proving the collision was resolved in the config file's
# favor. The other 16 are new credsonly-NN profiles found nowhere in config.

[nimbus]
aws_access_key_id     = AKIAFAKECREDSNIMBUS1
aws_secret_access_key = fake-creds-nimbus-secret
note                   = credswins-nimbus-should-not-appear

[shouty-scale-a]
aws_access_key_id     = AKIAFAKECREDSSHOUTY1
aws_secret_access_key = fake-creds-shouty-secret
note                   = credswins-shouty-scale-a-should-not-appear

[mfa-a/ReadOnly]
aws_access_key_id     = AKIAFAKECREDSMFA0001
aws_secret_access_key = fake-creds-mfa-secret
note                   = credswins-mfa-a-readonly-should-not-appear

[org05-acct3/Admin]
aws_access_key_id     = AKIAFAKECREDSORG0001
aws_secret_access_key = fake-creds-org-secret
note                   = credswins-org05-acct3-admin-should-not-appear

EOF

n=0
while [ "$n" -le 15 ]; do
	nn=$(printf '%02d' "$n")
	cat >>"$CREDS" <<EOF
[credsonly-${nn}]
aws_access_key_id     = AKIAFAKECREDSONLY${nn}
aws_secret_access_key = fake-credsonly-${nn}-secret
note                   = scale-creds-only-${nn}

EOF
	n=$((n + 1))
done

echo "wrote $(grep -c '^\[profile ' "$CONFIG") config profiles to $CONFIG"
echo "wrote $(grep -c '^\[' "$CREDS") credentials sections to $CREDS"
